services:
  miniflux-to-instapaper:
    image: ghcr.io/dylanfrankcom/miniflux-to-instapaper:latest
    ports:
      - "5002:5002"
    environment:
      - MINIFLUX_WEBHOOK_SECRET=${MINIFLUX_WEBHOOK_SECRET}
      - INSTAPAPER_USERNAME=${INSTAPAPER_USERNAME}
      - INSTAPAPER_PASSWORD=${INSTAPAPER_PASSWORD}
      - WEBHOOK_HOST=0.0.0.0
      - WEBHOOK_PORT=5002
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
